os: Visual Studio 2015

version: '{build}'

clone_depth: 5

environment:
    CTEST_OUTPUT_ON_FAILURE: 1
    matrix:
    - MINGW_DIR: mingw

before_build:
    - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
    - set PATH=C:\%MINGW_DIR%\bin;%PATH%
    - cmake --version
    - echo "NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%"
    - if "%APPVEYOR_REPO_TAG%"=="true" (set CMAKE_BUILD_TYPE=Release) else (set CMAKE_BUILD_TYPE=Debug)
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ..

build_script:
    - cmake --build . --use-stderr --target all -- -j%NUMBER_OF_PROCESSORS%

