os: Visual Studio 2015

version: '{build}'

clone_depth: 5

environment:
    CTEST_OUTPUT_ON_FAILURE: 1
    matrix:
    - MINGW_DIR: mingw

before_build:
- set Path=%CD%\%MINGW_DIR%\bin;%Path%
#- mingw32-make --version
- cmake --version
- echo "NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%"
- if "%APPVEYOR_REPO_TAG%"=="true" (set CMAKE_BUILD_TYPE=Release) else (set CMAKE_BUILD_TYPE=Debug)
- cmake -H. -Bbuild\mingw -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% 

build_script:
- cmake --build build\mingw --use-stderr --target all --

