os: Visual Studio 2015

version: '{build}'

clone_depth: 5

environment:
    CTEST_OUTPUT_ON_FAILURE: 1

before_build:
- set Path=%CD%\%MINGW_DIR%\bin;%Path%
#- g++ --version
#- mingw32-make --version
- cmake --version
- echo "NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%"
- ps: (Get-Item "${Env:WINDBG_DIR}\dbghelp.dll").VersionInfo
- if "%APPVEYOR_REPO_TAG%"=="true" (set CMAKE_BUILD_TYPE=Release) else (set CMAKE_BUILD_TYPE=Debug)
- set ENABLE_COVERAGE=yes
- if "%APPVEYOR_REPO_TAG%"=="true" set ENABLE_COVERAGE=no
- if NOT "%MINGW_DIR%"=="mingw64" set ENABLE_COVERAGE=no
- cmake -H. -Bbuild\mingw -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DENABLE_COVERAGE=%ENABLE_COVERAGE% -DWINDBG_DIR="%WINDBG_DIR%"

build_script:
- cmake --build build\mingw --use-stderr --target all -- -j%NUMBER_OF_PROCESSORS%

