#define FIRMATA_ANALOG_IO                       1
#define FIRMATA_DIGITAL_IO                      2
#define FIRMATA_REPORT_ANALOG                   3
#define FIRMATA_REPORT_DIGITAL                  4
#define FIRMATA_SET_PIN_MODE                    5
#define FIRMATA_SET_DPIN_VALUE                  6
#define FIRMATA_PROTOCOL_VERSION                7
#define FIRMATA_SYSTEM_RESET                    8
#define FIRMATA_BYTE7                           9
#define FIRMATA_ON                             10
#define FIRMATA_OFF                            11
#define FIRMATA_INPUT                          12
#define FIRMATA_OUTPUT                         13
#define FIRMATA_ANALOG                         14
#define FIRMATA_PWM                            15
#define FIRMATA_SERVO                          16
#define FIRMATA_I2C                            17
#define FIRMATA_ONEWIRE                        18
#define FIRMATA_STEPPER                        19
#define FIRMATA_ENCODER                        20
#define FIRMATA_SERIAL                         21
#define FIRMATA_PULLUP                         22
#define FIRMATA_START_SYSEX                    23
#define FIRMATA_STOP_SYSEX                     24
#define FIRMATA_SYSEX_ID                       25
